### ISSUE TITLE
Office Error Code 30015-11 (-1073741790)

### ISSUE THREAD

**Issue by hijuuijj** [lixuy/KMS_VL_ALL#1]
After replacing "C:\Windows\System32\spp\store" folder I can't reinstall Office 2016 Pro Plus anymore. I get the error code 30015-11 (-1073741790)
I tried to fix it with "OfficeRemovePro.diagcab" and "Revo Uninstaller"...
Any idea?

**Comment by kkkgo** [comment]
Try :  
https://support.office.com/en-us/article/Uninstall-Office-from-a-PC-9dd49b83-264a-477a-8fcc-2fdf5dbf61d8  
https://gallery.technet.microsoft.com/office/Uninstall-Office-2016-6f3fa204  
I suggest you reinstall your windows.
