### ISSUE TITLE
Doesn't work on Server 2016 

### ISSUE THREAD

**Issue by fire1ce** [lixuy/KMS_VL_ALL#2]
Build 14393.rs1_release_1.80402-1758

**Comment by kkkgo** [comment]
Any error?

**Comment by fire1ce** [comment]
no errors. here's a screenshot: https://3os.org/vcv6bp/VPw5WwFOnf.png
the server version has need updated since i've opened the issue. Here is the server's info screen:
https://3os.org/vcv6bp/lYDKAMg8oc.png
