### ISSUE TITLE
The system cannot find the batch label specified - CreateTask

### ISSUE THREAD

**Issue by GieltjE** [lixuy/KMS_VL_ALL#4]
Using release 32 on Win 10 pro X64 results in:

`Local KMS Emulator will be installed on your computer. Continue? [y/n]: Y

============================================================

Adding File...
"C:\WINDOWS\system32\SppExtComObjHook.dll"

Adding Registry Keys...
"HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SppExtComObj.exe"
"HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\osppsvc.exe"
The system cannot find the batch label specified - CreateTask

============================================================

Done.

It is recommended to exclude this file in the Antivirus protection.
"C:\WINDOWS\system32\SppExtComObjHook.dll"

Now run the file Activate.cmd to complete the Auto Renewal Activation.

Press any key to exit.`

**Comment by kkkgo** [comment]
There are CRLF error in release. Fixed.
