### ISSUE TITLE
The system cannot find the batch label specified - CreateTask

### ISSUE THREAD

**Issue by dalarso** [lixuy/KMS_VL_ALL#5]
The system cannot find the batch label specified - CreateTask while using auto renewal setup. Using version 32 on Windows 10 1903.

**Comment by kkkgo** [comment]
may be download error . try this link again https://github.com/kkkgo/KMS_VL_ALL/archive/master.zip

**Comment by dalarso** [comment]
Still the same error on multiple machines for me.

**Comment by GieltjE** [comment]
See #4 can be fixed by e.g. notepad++ convert to windows line endings.
