### ISSUE TITLE
My multi activator

### ISSUE THREAD

**Issue by FazCodeFR** [lixuy/KMS_VL_ALL#8]
Hello, I don't usually create issues on github but, here's a project of mine that might interest you. :
 https://github.com/ABOATDev/UnlockSoftwares

**Comment by CardcaptorRLH85** [comment]
Don't do this.  Blatant advertising of a project in an issue for another project is considered [spam](https://help.github.com/en/github/site-policy/github-acceptable-use-policies#9-spam-and-inauthentic-activity-on-github).

**Comment by Nakilon** [comment]
Is it some kind of joke to link to "GitHub Acceptable Use Policies" in KMS repo?
